use_default_settings: true

server:
  secret_key: "CHANGE_ME"
  image_proxy: true
  public: false
  limiter: false

general:
  debug: false
  instance_name: "Home SearXNG"

search:
  safe_search: 0
  autocomplete: "duckduckgo"

outgoing:
  useragent_suffix: "HA-Private-Instance"
  request_timeout: 2.0

engines:
  - name: duckduckgo
    disabled: false
  - name: brave
    disabled: false
  - name: wikipedia
    disabled: false
  - name: google
    disabled: true
  - name: bing
    disabled: true
